version: "3.5"

services:
  api01: &api
    image: morbacherik/rinha-backend
    hostname: api
    environment:
      - DB_URL=postgresql://root:root@db:5432/rinha
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "400MB"

  api02:
    <<: *api
    environment:
      - DB_URL=postgresql://root:root@db:5432/rinha
      - PORT=8082
    hostname: api
    ports:
      - "8082:8082"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - db
    ports:
      - "9999:9999"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "150MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

